set datestyle to sql,dmy;

/*DROP TABLE CLIENTE, TIENDA, REPARTIDOR, PRODUCTO, PEDIDO_PRODUCTO, PEDIDO CASCADE;*/

CREATE TABLE CLIENTE(
	IDCLIENTE SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	APATERNO VARCHAR(20) NOT NULL,
	APMATERNO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	CORREO VARCHAR(40) NOT NULL,
	CONTRASENA VARCHAR(20) NOT NULL,
	UNIQUE(CORREO)
);


CREATE TABLE TIENDA(
	IDTIENDA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	GIRO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	LATITUD DECIMAL(10,8),
	LONGITUD DECIMAL(10,8),
	CORREO VARCHAR(40) NOT NULL,
	CONTRASENA VARCHAR(20) NOT NULL,
	ENCARGADO VARCHAR(40) NOT NULL,
	UNIQUE(CORREO)
);

CREATE TABLE PRODUCTO(
	IDPRODUCTO SERIAL PRIMARY KEY,
	IDTIENDA INT REFERENCES TIENDA(IDTIENDA),
	NOMBRE VARCHAR(40) NOT NULL,
	DESCRIPCION TEXT NOT NULL,
	PRECIO NUMERIC NOT NULL,
	STOCK INT NOT NULL
);

CREATE TABLE REPARTIDOR(
	IDREPARTIDOR SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	APATERNO VARCHAR(20) NOT NULL,
	APMATERNO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	CORREO VARCHAR(40) NOT NULL,
	CONTRASENA VARCHAR(20) NOT NULL,
	UNIQUE(CORREO)
);

CREATE TABLE PEDIDO(
	IDPEDIDO SERIAL PRIMARY KEY,
	IDCLIENTE INT REFERENCES CLIENTE(IDCLIENTE),
	IDREPARTIDOR INT REFERENCES REPARTIDOR(IDREPARTIDOR),
	IDTIENDA INT REFERENCES TIENDA(IDTIENDA),
	LATITUD DECIMAL(10,8),
	LONGITUD DECIMAL(10,8),
	DESCRIPCION TEXT,
	FECHA DATE NOT NULL,
	ENTREGADO BOOLEAN,
	PAGADO BOOLEAN
);

CREATE TABLE PEDIDO_PRODUCTO(
	IDPEDIDO INT REFERENCES PEDIDO(IDPEDIDO),
	IDPRODUCTO INT REFERENCES PRODUCTO(IDPRODUCTO),
	CANTIDAD INT
);

