set datestyle to sql,dmy;

CREATE TABLE CLIENTE(
	IDCLIENTE SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30),
	APATERNO VARCHAR(20),
	APMATERNO VARCHAR(20),
	DIRECCION VARCHAR(100),
	TELEFONO VARCHAR(15),
	CORREO VARCHAR(40),
	CONTRASENA VARCHAR(20),
	LATITUD DECIMAL(10,8),
	LONGITUD DECIMAL(10,8)
);


CREATE TABLE TIENDA(
	IDTIENDA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30),
	GIRO VARCHAR(20),
	DIRECCION VARCHAR(100),
	LATITUD DECIMAL(10,8),
	LONGITUD DECIMAL(10,8),
	CORREO VARCHAR(40),
	CONTRASENA VARCHAR(20),
	ENCARGADO VARCHAR(40)
);

CREATE TABLE PRODUCTO(
	IDPRODUCTO SERIAL PRIMARY KEY,
	IDTIENDA INT REFERENCES TIENDA(IDTIENDA),
	NOMBRE VARCHAR(40),
	DESCRIPCION TEXT,
	PRECIO NUMERIC,
	STOCK INT
);

CREATE TABLE REPARTIDOR(
	IDREPARTIDOR SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30),
	APATERNO VARCHAR(20),
	APMATERNO VARCHAR(20),
	DIRECCION VARCHAR(100),
	TELEFONO VARCHAR(15),
	CORREO VARCHAR(40),
	CONTRASENA VARCHAR(20)
);

CREATE TABLE PEDIDO(
	IDPEDIDO SERIAL PRIMARY KEY,
	IDCLIENTE INT REFERENCES CLIENTE(IDCLIENTE),
	IDREPARTIDOR INT REFERENCES REPARTIDOR(IDREPARTIDOR),
	IDTIENDA INT REFERENCES TIENDA(IDTIENDA),
	LATITUD DECIMAL(10,8),
	LONGITUD DECIMAL(10,8),
	DESCRIPCION TEXT,
	FECHA DATE,
	ENTREGADO BOOLEAN,
	PAGADO BOOLEAN
);

CREATE TABLE PEDIDO_PRODUCTO(
	IDPEDIDO INT REFERENCES PEDIDO(IDPEDIDO),
	IDPRODUCTO INT REFERENCES PRODUCTO(IDPRODUCTO),
	CANTIDAD INT
);

